### PR TITLE
Improve accessibility

### PR DESCRIPTION
**Pull request by clementbiron**
That changeset improve the accessibility Lighthouse score from 87 to 100 by:
- replacing the code exemple images in the homepage by accessible and coloured code examples as marked-up text
- updating primary color 
- ordering headings in sequentially-descending

image

image

### CODE REVIEW

**Review by Ndpnt — CHANGES_REQUESTED** [review]
Increase contrast for hover effect for links on the hero section

**Comment by Ndpnt** [comment]
Was it too difficult to replicate the same difference as seen in the previous image for the "Analyzing" part, or did you choose not to attempt it?
Capture d’écran 2024-04-16 à 09 57 42

**Comment by Ndpnt** [comment]
Great work on transforming the images into actual code examples, a nice improvement! 👏

**Comment by clementbiron** [comment]
Thanks @Ndpnt  for your pertinent feedback, I've made some changes to reflect this.

**Review by Ndpnt — APPROVED** [review]

**Pull request merged**
